name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  SecurityCheck:
    name: Check for Security
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks.."
          # Replace with actual security check commands
          sleep 5s

  BuildNDeploy:
    name: BuildNDeploy
    needs: SecurityCheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Manually Trigger JMETER Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.R_ACCESS_TOKEN }}  
        run: |
          # Trigger the workflow
          response=$(curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/Zbr123/revealapi/actions/workflows/JMeterTest.yml/dispatches \
            -d '{"ref":"main"}')
          echo "Workflow dispatched. Response: $response"

      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          npm install --force
          
      - name: Build and Deploy
        run: |
          echo "Building..."
           npm run build
          echo "Deploying..."
          # npm run deploy
          # Or if you're just starting a server:
           npm run start