name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  SecurityCheck:
    name: Check for Security
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Running Security Checks.."
          sleep 5s

  BuildNDeploy:
    name: BuildNDeploy
    needs: SecurityCheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
  
              
      - name: Manually Trigger JMETER Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.R_ACCESS_TOKEN }}  
        run: |
          # Trigger the workflow
          response=$(curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            https://github.com/Zbr123/revealapi/blob/main/.github/workflows/JMeterTest.yml \
            -d '{"ref":"main"}')
          echo "Workflow dispatched. Response: $response"

          
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies ..."
          npm install --force
          echo "Building and Deploying..."
          nohup npm run start > /dev/null 2>&1 Z
